### ISSUE TITLE
how i can change background color for all bottom bar from white to any color

### ISSUE THREAD

**Issue by alibeliedy96** [mi-ghanshyam/floating_bottom_bar#1]

**Comment by smunshimi** [comment]
Hi @alibeliedy96,

Now there's a `barColor` and `barGradient` property which you can use to your needs.

**Comment by mariomurrent-softwaresolutions** [comment]
> Hi @alibeliedy96,
> 
> Now there's a `barColor` and `barGradient` property which you can use to your needs.

Where do this properties exist? They are not even available

**Comment by AnujMI297** [comment]
@mariomurrent-softwaresolutions As @smunshimi said there is a provision to change the color by giving the value to either `barColor` or `barGradient` inside `AnimatedBottomNavigationBar`.

**Comment by deep-mindinventory** [comment]
Check the latest version for updates. I just wanted to let you know that I'm closing this issue for now. Reopen it if you do not find the above-mentioned solution.
