### ISSUE TITLE
can't dismiss bottomBarCenterModel 

### ISSUE THREAD

**Issue by AbdelrahmanElmarakby10** [mi-ghanshyam/floating_bottom_bar#2]
when I open the bottomBarCenterModel I can't dismiss it when I want and unless I click in an option it will stick there

**Comment by mariomurrent-softwaresolutions** [comment]
Thats a good point - would be nice if this would be implemented.
As quick fix you can create an own close button as additional center modal button

**Comment by AnujMI297** [comment]
@AbdelrahmanElmarakby10 @mariomurrent-softwaresolutions As per your suggestion we have added the close button by default to close the `bottomBarCenterModel`.

**Comment by deep-mindinventory** [comment]
@mariomurrent-softwaresolutions Please check latest version. Thanks.
