### ISSUE TITLE
How can we Load different screens on each tab click in the container as like bottom navigation bar?

### ISSUE THREAD

**Issue by sankar07** [mi-ghanshyam/floating_bottom_bar#3]

**Comment by AnujMI297** [comment]
@sankar07  we have provided the index callback inside the `onTap` of `BottomBarItem`. Moreover, we have added a new property called `controller` where you can give the initial index inside `FloatingBottomBarController` so that the bottom bar will automatically select that item as default.

**Comment by deep-mindinventory** [comment]
@sankar07 Please check the latest version. We have added a provision for the Controller.
