### ISSUE TITLE
Bottom bar looks different then in the screenshot

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [mi-ghanshyam/floating_bottom_bar#4]
I took the example and just updated the icons and colors, but it looks different on the iOS device. The center button has no nice border like in the screenshot.

![IMG_BE62ED3F8F83-1](https://user-images.githubusercontent.com/5072806/215340104-eac637ef-e168-4148-9257-8f799ac98126.jpeg)

**Comment by AnujMI297** [comment]
@mariomurrent-softwaresolutions can you please share your code snippet? It is not regenerated with iPhone x.
![F35C0C52-2266-4C57-B921-E83DF28062AD](https://user-images.githubusercontent.com/97672970/234791820-5cbfc978-4039-45b5-b820-5a630a0e0cfa.jpg)

**Comment by mariomurrent-softwaresolutions** [comment]
I have tested it on the iPhone 14 Pro Max, just with the sample code. Sorry, right now I don't have the code anymore.

**Comment by AnujMI297** [comment]
@mariomurrent-softwaresolutions we are going to publish the new package. Please check the same case in that package and reopen the issue if needed.
