### ISSUE TITLE
Not floating

### ISSUE THREAD

**Issue by Maxmontgelas** [mi-ghanshyam/floating_bottom_bar#6]
Sadly though it is lacking the floating part....

**Comment by jaydeepkaria-mi** [comment]
Hi @Maxmontgelas, Can you please tell us what issue you are facing in floating part so we can check that in detail because for us it is working.

**Comment by jaydeepkaria-mi** [comment]
Closing this issue for now. Please check it with the [latest version](https://pub.dev/packages/floating_bottom_bar) if you are still facing the issue or not. Feel free to reopen. Thanks
